### PR TITLE
Update SERVERLIST.json

### PR DESCRIPTION
**Pull request by rcon420**

### CODE REVIEW

**Comment by JMorell** [comment]
The maps do not have to be added to fastdl file.

**Comment by rcon420** [comment]
> The maps do not have to be added to fastdl file.

removed them, tnx

**Comment by xLeviNx** [comment]
> > The maps do not have to be added to fastdl file.
> 
> removed them, tnx

as in they don't need to be quoted in the txt file. Maps themselves should be available in the fastdl directory

**Comment by rcon420** [comment]
> > > The maps do not have to be added to fastdl file.
> > 
> > 
> > removed them, tnx
> 
> as in they don't need to be quoted in the txt file. Maps themselves should be available in the fastdl directory

yes i meant that i removed them from txt files

**Pull request merged**
